elasticjob:
  regCenter:
    serverLists: localhost:2181
    namespace: elasticjob-lite-springboot
  jobs:
    dataflowJob:
      elasticJobClass: com.example.demo.elasticjob.SpringBootDataflowJob
      cron: 0/30 * * * * ?
      shardingTotalCount: 3
      shardingItemParameters: 0=Beijing00,1=Shanghai11,2=Guangzhou22
      overwrite: true
spring:
  datasource:
    url: jdbc:mysql://10.88.26.61:8066/db_einvoice_platform?characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&requireSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: user_einvoice
    password: user_einvoice
    type: com.zaxxer.hikari.HikariDataSource
server:
  port: 8079